version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: EventClean
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - "5431:5432"
    restart: always
